version: 2.1

orbs:
  node: circleci/node@2.0.3
  artifactory: circleci/artifactory@1.0.0
  aws-ecs: circleci/aws-ecs@2.0.0
  aws-cli: circleci/aws-cli@1.4.0

jobs:
  build-scan:
    docker:
      - image: cimg/node:13.10.1
    steps:
      - checkout
      - setup_remote_docker
      - artifactory/install
      - artifactory/configure:
          artifactory-key: ARTIFACTORY_API_KEY
          artifactory-url: ARTIFACTORY_URL
          artifactory-user: ARTIFACTORY_USER
#      - run:
#          name: Configure NPM
#          command: |
#            jfrog rt npmc --repo-resolve=npm --repo-deploy=npm --server-id-resolve=$ARTIFACTORY_SERVER --server-id-deploy=$ARTIFACTORY_SERVER
#      - run:
#          name: NPM Install
#          command: |
#            jfrog rt npm-install --build-name=demo-build --build-number=$CIRCLE_SHA1
#      - run:
#          name: NPM Publish
#          command: |
#            jfrog rt npm-publish --build-name=demo-build --build-number=$CIRCLE_SHA1
#      - run:
#          name: Build Publish
#          command: |
#            jfrog rt build-publish --build-name=demo-build --build-number=$CIRCLE_SHA1
      - run:
          name: Build Docker image
          command: |
            docker build -t $ARTIFACTORY_SERVER/docker/demo-build:$CIRCLE_SHA1 .
#      - run:
#          name: Log in to Docker
#          command: |
#            docker login --username=$ARTIFACTORY_USER --password=$ARTIFACTORY_API_KEY $ARTIFACTORY_SERVER
      - run:
          name: Docker Push
          command: |
            jfrog rt dp $ARTIFACTORY_SERVER/docker/demo-build:$CIRCLE_SHA1 docker --build-name=demo-build --build-number=$CIRCLE_SHA1
      - run:
          name: Build Publish with Env Vars
          command: |
            jfrog rt bce demo-build $CIRCLE_SHA1
            jfrog rt bp demo-build $CIRCLE_SHA1
            jfrog rt bs demo-build $CIRCLE_SHA1
      - run:
          name: Build Xray Scan
          command: |
            jfrog rt bs demo-build $CIRCLE_SHA1
  promote:
    docker:
      - image: cimg/node:13.10.1
    steps:
      - checkout
      - artifactory/install
      - artifactory/configure:
          artifactory-key: ARTIFACTORY_API_KEY
          artifactory-url: ARTIFACTORY_URL
          artifactory-user: ARTIFACTORY_USER
      - run:
          name: Promote
          command: jfrog rt bpr demo-build $CIRCLE_SHA1 docker-local

workflows:
  build_test_deploy:
    jobs:
      - build-scan
      - hold:
          type: approval
          requires:
            - build-scan
          filters:
            branches:
              only: master
      - promote:
          requires:
            - hold
          filters:
            branches:
              only: master
      - aws-ecs/deploy-service-update:
          cluster-name: 'jfrog-circleci-demo'
          container-image-name-updates: 'container=$ARTIFACTORY_SERVER/docker/demo-build,tag=${CIRCLE_SHA1}'
          family: 'jfrog-circleci-demo-service'
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-region: AWS_DEFAULT_REGION
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          requires:
            - promote



